# Node Image
FROM node:14-alpine as build

# Create Working Directory
WORKDIR /usr/src/app

# Copy package.json files To Working Directory
COPY package*.json ./

# Install Node Modules And Dependancies
RUN npm install

# Copy All Files
COPY . .

# Build React App
RUN npm run build

# Nginx Image
FROM nginx:1.18.0-alpine

# Copy React Build To Nginx Public Folder
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose Port 80
EXPOSE 80

# Run Command To Start Nginx
CMD ["nginx", "-g", "daemon off;"]