version: "3.4"

x-common-variables: &common-variables
  DB_USER: root
  DB_PASS: root
  DB_NAME: chatapp
  REACT_APP_API_URL: http://api:5000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      DB_HOST: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  api:
    build: ./api
    depends_on:
      - mysql
    expose:
      - 5000
    environment:
      <<: *common-variables
      DB_HOST: mysql
    ports:
      - 5000:5000
    volumes:
      - ./api:/server
    links:
      - mysql
    command: npm run dev
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    depends_on:
      - api
    ports:
      - 80:80
